# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZIzetbtd3Aib4el9DApHcFHRXUkTi90
"""

import matplotlib.pyplot as plt

import numpy as np

x=np.array([0,6])
y=np.array([0,250])


plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,3,5,7,9,11,13,15,17,19,21])
y=np.array([2,11,1,16,-2,17,1,18,0,20,2])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt

import numpy as np

y=np.array([3,8,1,10])

plt.plot(y, marker='o')
plt.show()

import matplotlib.pyplot as plt

import numpy as np

y=np.array([3,8,1,10])

plt.plot(y, marker='o',ms=20)
plt.show()

import matplotlib.pyplot as plt

import numpy as np

y=np.array([3,8,1,10])

plt.plot(y, marker='o',mec='r')
plt.show()

import matplotlib.pyplot as plt

import numpy as np


x1=np.array([0,1,2,3])
y1=np.array([3,8,1,10])
x2=np.array([0,1,2,3])
y2=np.array([6,7,2,11])


plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt

import numpy as np

y=np.array([3,8,1,10])

plt.plot(y, marker='o', ms=20, mfc='r')
plt.show()

import matplotlib.pyplot as plt

import numpy as np

x=np.array([0,1,2,3,])
y=np.array([3,8,1,10])

plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x= np.array([0,3,0,3,3,0,1,5,1,5])
y= np.array([0,10,10,0,5,5,0,10,2,3])

plt.scatter(x,y)
plt.show()